// Stub ActivityType.h for builds without libkineto
#pragma once

namespace libkineto {

enum class ActivityType {
  CPU_OP = 0,
  CPU_INSTANT_EVENT,
  USER_ANNOTATION,
  GPU_USER_ANNOTATION,
  GPU_MEMCPY,
  GPU_MEMSET,
  CONCURRENT_KERNEL,
  EXTERNAL_CORRELATION,
  CUDA_RUNTIME,
  CUDA_DRIVER,
  CPU_FILE_IO,
  PYTHON_FUNCTION,
  OVERHEAD,
  MTIA_CCP_EVENTS,
  CUDA_SYNC,
  GLOW_RUNTIME,
  MTIA_RUNTIME,
  CUDA_PROFILER_RANGE,
  HPU_OP,
  HPU_RUNTIME,
  XPU_RUNTIME,
  XPU_DRIVER,
  COLLECTIVE_COMM,
  MTIA_COUNTERS,
  MTIA_INSIGHT,
  PRIVATEUSE1_RUNTIME,
  PRIVATEUSE1_DRIVER,
  NUM_ACTIVITY_TYPES
};

} // namespace libkineto
